/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.asksteved.probe;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ProbePluginTest {
    @Test void TestSomething() {
        ProbePlugin classUnderTest = new ProbePlugin();
        assertNotNull(classUnderTest.toString(), "placeholder");
    }
}
